//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class InventoryRes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal InventoryRes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("InventoryControl.Resources.InventoryRes", typeof(InventoryRes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back To List.
        /// </summary>
        public static string Action_BackToList {
            get {
                return ResourceManager.GetString("Action_BackToList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this?.
        /// </summary>
        public static string Action_CheckDelete {
            get {
                return ResourceManager.GetString("Action_CheckDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string Action_Create {
            get {
                return ResourceManager.GetString("Action_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New.
        /// </summary>
        public static string Action_CreateNew {
            get {
                return ResourceManager.GetString("Action_CreateNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Action_Delete {
            get {
                return ResourceManager.GetString("Action_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Action_Edit {
            get {
                return ResourceManager.GetString("Action_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Action_Save {
            get {
                return ResourceManager.GetString("Action_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string Action_ViewDetails {
            get {
                return ResourceManager.GetString("Action_ViewDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available number of units is mandatory..
        /// </summary>
        public static string Error_AvailableNoOfUnitsMandatory {
            get {
                return ResourceManager.GetString("Error_AvailableNoOfUnitsMandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name is mandatory..
        /// </summary>
        public static string Error_NameMandatory {
            get {
                return ResourceManager.GetString("Error_NameMandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nagative values not allowed..
        /// </summary>
        public static string Error_NegativeValuesNotAllowed {
            get {
                return ResourceManager.GetString("Error_NegativeValuesNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit price is mandatory..
        /// </summary>
        public static string Error_UnitPriceMandatory {
            get {
                return ResourceManager.GetString("Error_UnitPriceMandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Availabe No Of Units.
        /// </summary>
        public static string Label_AvailabeNoOfUnits {
            get {
                return ResourceManager.GetString("Label_AvailabeNoOfUnits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Label_Name {
            get {
                return ResourceManager.GetString("Label_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reorder Level.
        /// </summary>
        public static string Label_ReorderLevel {
            get {
                return ResourceManager.GetString("Label_ReorderLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit Price.
        /// </summary>
        public static string Label_UnitPrice {
            get {
                return ResourceManager.GetString("Label_UnitPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory Item.
        /// </summary>
        public static string Title_InventoryItem {
            get {
                return ResourceManager.GetString("Title_InventoryItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inventory Items.
        /// </summary>
        public static string Title_InventoryItemList {
            get {
                return ResourceManager.GetString("Title_InventoryItemList", resourceCulture);
            }
        }
    }
}
